config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :follows
  resources :upvotes
  resources :books
  resources :authors
  resources :users
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  before_action :set_upvote, only: [:show, :edit, :update, :destroy]

  # GET /upvotes
  # GET /upvotes.json
  def index
    @upvotes = Upvote.all
  end

  # GET /upvotes/1
  # GET /upvotes/1.json
  def show
  end

  # GET /upvotes/new
  def new
    @upvote = Upvote.new
  end

  # GET /upvotes/1/edit
  def edit
  end

  # POST /upvotes
  # POST /upvotes.json
  def create
    @upvote = Upvote.new(upvote_params)

    respond_to do |format|
      if @upvote.save
        format.html { redirect_to @upvote, notice: 'Upvote was successfully created.' }
        format.json { render :show, status: :created, location: @upvote }
      else
        format.html { render :new }
        format.json { render json: @upvote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /upvotes/1
  # PATCH/PUT /upvotes/1.json
  def update
    respond_to do |format|
      if @upvote.update(upvote_params)
        format.html { redirect_to @upvote, notice: 'Upvote was successfully updated.' }
        format.json { render :show, status: :ok, location: @upvote }
      else
        format.html { render :edit }
        format.json { render json: @upvote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /upvotes/1
  # DELETE /upvotes/1.json
  def destroy
    @upvote.destroy
    respond_to do |format|
      format.html { redirect_to upvotes_url, notice: 'Upvote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upvote
      @upvote = Upvote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upvote_params
      params.require(:upvote).permit(:user_id, :book_id)
    end
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/views/upvotes/_form.html.erb
<%= form_with(model: upvote, local: true) do |form| %>
  <% if upvote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(upvote.errors.count, "error") %> prohibited this upvote from being saved:</h2>

      <ul>
      <% upvote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.text_field :book_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/upvotes/edit.html.erb
<h1>Editing Upvote</h1>

<%= render 'form', upvote: @upvote %>

<%= link_to 'Show', @upvote %> |
<%= link_to 'Back', upvotes_path %>

app/views/upvotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Upvotes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @upvotes.each do |upvote| %>
      <tr>
        <td><%= upvote.user %></td>
        <td><%= upvote.book %></td>
        <td><%= link_to 'Show', upvote %></td>
        <td><%= link_to 'Edit', edit_upvote_path(upvote) %></td>
        <td><%= link_to 'Destroy', upvote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upvote', new_upvote_path %>

app/views/upvotes/new.html.erb
<h1>New Upvote</h1>

<%= render 'form', upvote: @upvote %>

<%= link_to 'Back', upvotes_path %>

app/views/upvotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @upvote.user %>
</p>

<p>
  <strong>Book:</strong>
  <%= @upvote.book %>
</p>

<%= link_to 'Edit', edit_upvote_path(@upvote) %> |
<%= link_to 'Back', upvotes_path %>